version: "3.9"

services:
  db:
    container_name: mondi_postgres
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
